<?php

declare(strict_types=1);

use Nextras\Migrations\Bridges;
use Nextras\Migrations\Controllers;
use Nextras\Migrations\Drivers;
use Nextras\Migrations\Extensions;

// Load Nette Framework or autoloader generated by Composer
require __DIR__ . '/../vendor/autoload.php';

$configurator = new Nette\Configurator;

$configurator->enableDebugger(__DIR__ . '/../logs');
$configurator->setTempDirectory(__DIR__ . '/../temp');

$configurator->createRobotLoader()
    ->register();

// Create Dependency Injection container from common.neon file
$configurator->addConfig(__DIR__ . '/common.neon');

if (file_exists(__DIR__ . "/../config/local.neon")) {
    $configurator->addConfig(__DIR__ . '/../config/local.neon');
} else {
    $configurator->addConfig(__DIR__ . '/../config/production.neon');
}

$configurator->setTimeZone('Europe/Prague');
$dic = $configurator->createContainer();

$conn = $dic->getByType('Nextras\Dbal\Connection');
$dbal = new Bridges\NextrasDbal\NextrasAdapter($conn);
$driver = new Drivers\MySqlDriver($dbal);

if (PHP_SAPI === 'cli') {
    $controller = new Controllers\ConsoleController($driver);
} else {
    $controller = new Controllers\HttpController($driver);
}

$controller->addGroup('structure', __DIR__ . '/structure');
$controller->addGroup('init-data', __DIR__ . '/init-data', ['structure']);
$controller->addGroup('test-data', __DIR__ . '/test-data', ['init-data']);
$controller->addGroup('production-data', __DIR__ . '/production-data', ['init-data']);
$controller->addExtension('sql', new Extensions\SqlHandler($driver));

if ($dic->parameters['productionMode']) {
    printWarningMessage();
    exit();
}

$controller->run();

function printWarningMessage()
{
    echo '<div class="output">
			<h3 class="error">
				<br><br>!!! FORBIDDEN !!!<br><br><br>
			</h3>
		</div>';
}
